In [1]:
from localise.load import load_features

In [2]:
from localise.load import load_labels

In [4]:
import torch
from localise.flatten_forward import FlexibleClassifier

In [14]:
m = FlexibleClassifier(layer=torch.nn.Sequential(torch.nn.Linear(75, 2), torch.nn.ReLU(), torch.nn.Linear(2, 2)), is_crf=True, n_kernels=2)

In [18]:
m(batch)

tensor([[4.4640e-03, 9.9554e-01],
        [9.4148e-04, 9.9906e-01],
        [5.3799e-04, 9.9946e-01],
        ...,
        [6.3642e-04, 9.9936e-01],
        [5.8817e-04, 9.9941e-01],
        [9.7453e-04, 9.9903e-01]], grad_fn=<SoftmaxBackward0>)

In [8]:
from glob import glob
import os
subject='100610'
path_to_data='/Users/yqzheng/PycharmProjects/python-localise/tests/test_data'
target_list = [os.path.split(f)[-1] for f in sorted(glob(path_to_data+'/'+subject+'/streamlines/left/seeds_to_*'))]

batch = load_features(subject=os.path.join(path_to_data,subject), 
              mask_name='roi/left/tha_small.nii.gz', 
              target_path='streamlines/left', 
              target_list=target_list,power=[1], gamma=[0, 0.1])


In [5]:
y = load_labels(subject=os.path.join(path_to_data,subject), 
              mask_name='roi/left/tha_small.nii.gz', 
                label_name='high-quality-labels/left/labels.nii.gz'
               )
y

tensor([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]])

In [25]:
m = torch.nn.Sequential( torch.nn.Linear(75, 2), torch.nn.Linear(2, 2))
m.parameters

<bound method Module.parameters of Sequential(
  (0): Linear(in_features=75, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)>

In [4]:
subject=os.path.join(path_to_data,'100610')
mask_name='roi/left/tha_small.nii.gz'
label_name='high-quality-labels/left/labels.nii.gz'
from localise.load import load_labels
labels = load_labels(subject, mask_name, label_name)
labels.shape
list(labels.shape) == [2, 4142]


True

In [4]:
from localise.flatten_forward import Affine

In [7]:
from localise.flatten_forward import AffineCRF

In [6]:
batch.X.shape

torch.Size([75, 4142])

In [8]:
m = AffineCRF(75, 2, 2)
m.b

Parameter containing:
tensor([[-2.0912],
        [ 0.3264]], requires_grad=True)

In [9]:
m(batch)

tensor([[5.3047, 7.4936, 8.2041,  ..., 6.7160, 7.0804, 6.4152],
        [0.7394, 1.0397, 1.0449,  ..., 0.6753, 0.9143, 1.2409]],
       grad_fn=<SubBackward0>)